### ISSUE TITLE
What is the reason to block so many sites?

### ISSUE THREAD

**Issue by Sraw** [missdeer/blocklist#19]
I don't fully understand why. It seems that some normal sites are also be blocked such as `sendgrid.com` which is used by eversource(an electricity company)

**Comment by missdeer** [comment]
@Sraw it merges content from several sources, all sources are list at https://github.com/missdeer/blocklist/blob/7f33f0f1ef7643a5312c9f7ca1be296df4fb9627/update.go#L20
